printshellcmds: True
keep-going: True
use-singularity: True
singularity-args: "--cleanenv -B $(pwd) -B /nfs/turbo/umms-brcfpipeline/references:/nfs/turbo/umms-brcfpipeline/references:ro"
singularity-prefix: /nfs/turbo/umms-brcfpipeline/snakemake_singularity
cores: 20
resources: memoryInGb=64
