language: python
python:
    - "3.6"
branches:
    only:
        - master
        - develop
install:
    # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - source "$HOME/miniconda/etc/profile.d/conda.sh"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

    - conda create -f ${TRAVIS_BUILD_DIR}/envs/watermelon_test.yaml

before_script:
    - conda activate watermelon_test

script:
    - nosetests --exclude=cutadapt --exclude=concat_reads

notifications:
    email:
        - trsaari@umich.edu
        - cgates@umich.edu
        - jingquma@umich.edu
