#samples:
#    Sample_01: Wt
#    Sample_02: Mut1
#    Sample_03: Mut2
#    Sample_04: Mut2
samples:
    Sample_01: Wt
    Sample_02: Wt
    Sample_03: Mut
    Sample_04: Mut
genome:
    hg19
gtf:
    /ccmb/BioinfCore/Projects/Manjusha/Genomes/iGenomes/Homo_sapiens_UCSC_hg19/Homo_sapiens/UCSC/hg19/Annotation/Genes/genes.gtf
bowtie2_index:
    /ccmb/BioinfCore/Projects/Manjusha/Genomes/iGenomes/Homo_sapiens_UCSC_hg19/Homo_sapiens/UCSC/hg19/Sequence/Bowtie2Index/genome
fasta:
    /ccmb/BioinfCore/Projects/Manjusha/Genomes/iGenomes/Homo_sapiens_UCSC_hg19/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa
transcriptome_index:
    hg19/hg19_transcriptome
comparisons:
#    Mut1_Mut2_Wt: Mut1_Mut2_Wt
#    Wt_Mut2: Wt_Mut2
#    Mut1_Mut2: Wt_Mut2
    Wt_Mut: Wt_Mut
fold_change:
    1.5
