printshellcmds: True
keep-going: True
use-singularity: True
singularity-args: "--cleanenv -B $(pwd) -B /nfs/turbo/umms-brcfpipeline/references:/nfs/turbo/umms-brcfpipeline/references:ro"
singularity-prefix: /nfs/turbo/umms-brcfpipeline/snakemake_singularity
slurm: True
default-resources: [slurm_account=bfx_project99, slurm_partition=standard, nodes=1, cpus_per_task=1, mem_mb=2000, runtime=120]
latency-wait: 300
jobs: 144
