# config created 2019-05-20
# To do:
# ------
# 1) Review/adjust samples names
#     Note: names in config, must match the sample dir names in the input dir
# 2) Add a sample group for each sample
# 3) Add comparisons
# 4) Review genome and references
# 5) Review alignment options
# 6) Review trimming options

input_dir: /ccmb/BioinfCore/ActiveProjects/rcavalca/test_lumeng/inputs/01-source_samples

diffex:
    sample_descriptions_file: config/example_sample_descriptions_subset.csv
    comparison_file: config/example_comparisons.yaml

main_factors: yes    ^ yes ^ yes     ^ no ^ no ^ no ^ no
phenotypes: pheno  ^  Gend  ^  tiss  ^  pheno.Gend  ^  pheno.tiss  ^  Gend.tiss  ^  pheno.Gend.tiss
samples:
    Sample_59223:    NDM  ^  fem  ^  VAT  ^  NDM.fem  ^  NDM.VAT  ^  fem.VAT  ^  NDM.fem.VAT
    Sample_59224:    NDM  ^  fem  ^  SAT  ^  NDM.fem  ^  NDM.SAT  ^  fem.SAT  ^  NDM.fem.SAT
    Sample_59235:    NDM  ^  male  ^  VAT  ^  NDM.male  ^  NDM.VAT  ^  male.VAT  ^  NDM.male.VAT
    Sample_59236:    NDM  ^  male  ^  SAT  ^  NDM.male  ^  NDM.SAT  ^  male.SAT  ^  NDM.male.SAT
    Sample_59245:    DM  ^  fem  ^  VAT  ^  DM.fem  ^  DM.VAT  ^  fem.VAT  ^  DM.fem.VAT
    Sample_59246:    DM  ^  fem  ^  SAT  ^  DM.fem  ^  DM.SAT  ^  fem.SAT  ^  DM.fem.SAT
    Sample_59253:    DM  ^  male  ^  VAT  ^  DM.male  ^  DM.VAT  ^  male.VAT  ^  DM.male.VAT
    Sample_59254:    DM  ^  male  ^  SAT  ^  DM.male  ^  DM.SAT  ^  male.SAT  ^  DM.male.SAT
# phenotypes: pheno  ^  Gend  ^  tiss  ^  pheno.Gend  ^  pheno.tiss  ^  Gend.tiss  ^  pheno.Gend.tiss
comparisons:
    pheno:
    - DM_v_NDM
    Gend:
    - fem_v_male
    tiss:
    - VAT_v_SAT
    pheno.Gend:
    - NDM.male_v_DM.male
    - NDM.fem_v_DM.fem
    - NDM.fem_v_NDM.male
    - DM.fem_v_DM.male
    pheno.tiss:
    - DM.VAT_v_NDM.VAT
    - DM.SAT_v_NDM.SAT
    - DM.VAT_v_DM.SAT
    - NDM.VAT_v_NDM.SAT
    Gend.tiss:
    - fem.VAT_v_fem.SAT
    - male.VAT_v_male.SAT
    - fem.VAT_v_male.VAT
    - fem.SAT_v_male.SAT
    pheno.Gend.tiss:
    - DM.male.VAT_v_DM.male.SAT
    - DM.male.VAT_v_DM.fem.VAT
    - DM.male.VAT_v_NDM.male.VAT
    - NDM.male.VAT_v_NDM.fem.VAT
    - NDM.male.VAT_v_NDM.male.SAT
    - DM.fem.VAT_v_DM.fem.SAT
    - DM.fem.VAT_v_NDM.fem.VAT
    - NDM.fem.VAT_v_NDM.fem.SAT
    - NDM.male.SAT_v_NDM.fem.SAT
    - DM.fem.SAT_v_NDM.fem.SAT
    - DM.male.SAT_v_NDM.male.SAT
    - DM.male.SAT_v_DM.fem.SAT

genome: hg19
references:
    fasta: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/hg19/Sequence/genome.fa
    gtf: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/hg19/hg19_noRibo.gtf
rsem_ref_prefix: hg19_noRibo
alignment_options:
    read_length: 49
    library_type: fr-unstranded
    transcriptome_only: true
alignment_output_dir: alignment_results/
deliverables_output_dir: deliverables/
deseq2_adjustedPValue: 0.05
diffex_output_dir: diffex_results/
# fastq_screen:
#     aligner: bowtie2
#     reference_basedir: /nfs/med-bfx-common/pipelines/Watermelon/references/fastq_screen
#     species: human
#     subset: 100000
fold_change: 1.5
# insert_size:
#     downsample_readcount: 30000
#     pair_length: 500
trimming_options:
    base_quality_3prime: 13
    base_quality_5prime: 0
    trim_length_3prime: 0
    trim_length_5prime: 3
