input_dir:
    "/ccmb/BioinfCore/SoftwareDev/projects/Watermelon_spike/Tronson_RS1_tests/test_data/inputs/00-multiplexed_reads"
alignment_output_dir:
    "alignment_results"
diffex_output_dir:
    "diffex_results"

samples:
    Sample_61483: VVM
    Sample_61484: VVM
#    Sample_61485: VVM
#    Sample_61486: VLM
#    Sample_61487: VLM
#    Sample_61488: VLM
#    Sample_61489: LVM
    Sample_61490: LVM
    Sample_61491: LVM
#    Sample_61492: LLM
#    Sample_61493: LLM
#    Sample_61494: LLM
#    Sample_61495: VVF
#    Sample_61496: VVF
#    Sample_61497: VVF
#    Sample_61498: VLF
#    Sample_61499: VLF
#    Sample_61500: VLF
#    Sample_61501: LVF
#    Sample_61502: LVF
#    Sample_61503: LVF
#    Sample_61504: LLF
    Sample_61505: LLF
    Sample_61506: LLF

comparisons:
    VVM_v_LLF: VVM_v_LLF
#    LVM_v_LVF: LVM_v_LVF

fold_change:
    1.5

trimming_options:
    base_quality_5prime: 0
    base_quality_3prime: 0
    trim_length_5prime: 0
    trim_length_3prime: 3

alignment_options:
    transcriptome_only: True
    library_type: 0  # 1   # 2

genome:
    mm10

references:
#path to reference gtf file
    gtf: /ccmb/BioinfCore/SoftwareDev/projects/Watermelon_spike/Tronson_RS1_tests/test_data/inputs/references/mm10_tronson/genes.gtf
#    gtf: /ccmb/BioinfCore/Reference_Genomes/programs/tophat/mouse/mm10/Mus_musculus/UCSC/mm10/Annotation/Genes
# path to dir with bowtie index
    bowtie2_index: /ccmb/BioinfCore/Reference_Genomes/programs/tophat/mouse/mm10/Mus_musculus/UCSC/mm10/Sequence/BowtieIndex/bowtie2
#    bowtie2_index: /ccmb/BioinfCore/Reference_Genomes/programs/tophat/mouse/mm10/Mus_musculus/UCSC/mm10/Sequence/BowtieIndex
# path to entrez gene info file
    entrez_gene_info: /ccmb/BioinfCore/SoftwareDev/projects/Watermelon/genome_annotations/entrez_gene_info/2016_09_02/gene_info
#    entrez_gene_info: /ccmb/BioinfCore/SoftwareDev/projects/Watermelon/genome_annotations/entrez_gene_info/2016_09_02

