$schema: 'http://json-schema.org/draft-04/schema#'
title: Watermelon yaml schema
type: object
properties:
    genome:
        type: string
    samplesheet:
        type: string
        pattern: 'csv$'
    dirs:
        properties:
            alignment_output:
                type: string
            deliverables_output:
                type: string
            diffex_output:
                type: string
            report_output:
                type: string
            input:
                type: string
        required:
            - alignment_output
            - diffex_output
            - deliverables_output
            - report_output
            - input

    references:
        properties:
            annotation_tsv:
                type: string
            fasta:
                type: string
            gtf:
                type: string
    alignment_options:
        properties:
            read_length:
                type: integer
    diffex:
        properties:
            adjustedPValue:
                type: number
            linear_fold_change:
                type: number
            count_min_cutoff:
                type: number
    fastq_screen:
        properties:
            aligner:
                type: string
            reference_basedir:
                type: string
            species:
                type: string
            subset:
                type: integer
    trimming_options:
        properties:
            base_quality_3prime:
                type: integer
            base_quality_5prime:
                type: integer
            trim_length_3prime:
                type: integer
            trim_length_5prime:
                type: integer
required:
    - genome
    - samplesheet
    - dirs
    - references
    - alignment_options
    - diffex
