# config created 2020-08-20 14:19:32
# To do:
# ------
# 1) Review genome and references
# 2) Review report information
# 3) Review alignment, trimming, and fastq_screen options
# 4) Modify the diffex options - use the 'model_one' stanza as an example, and
#    set up the DESeq2 calls and results calls for the comparisons that match the analysis.

email:
    subject: watermelon_test_ds
    to: trsaari@umich.edu
watermelon_version: 1.5.0
samplesheet: /nfs/med-bfx-activeprojects/trsaari/sandbox/20200622_diffex_iso/samplesheet_rs10.abridged.csv
genome: GRCh38
references:
    fasta: /nfs/med-bfx-common/ENSEMBL_references/Homo_sapiens/GRCh38/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa
    gtf: /nfs/med-bfx-common/ENSEMBL_references/Homo_sapiens/GRCh38/Homo_sapiens.GRCh38.98.gtf
    annotation_tsv: /nfs/med-bfx-common/ENSEMBL_references/Homo_sapiens/GRCh38/Homo_sapiens.GRCh38.98_annotation.tsv
dirs:
    alignment_output: analysis_test_ds/alignment_results
    diffex_output: analysis_test_ds/diffex_results
    deliverables_output: analysis_test_ds/deliverables
    report_output: analysis_test_ds/report
    input: /nfs/med-bfx-activeprojects/trsaari/sandbox/20200622_diffex_iso/inputs/01-source_samples
report_info: #These strings are used directly in the report
    project_name: Example Project
    prep_description: Prior tissue or cell isolation along with generation of total
        RNA was performed by the researcher. Sequencing was performed by the UM Advanced
        Genomics Core, with libraries constructed and subsequently subjected to 150
        paired end cycles on the NovaSeq-6000 platform (Illumina).
    analyst_name: Travis Saari
trimming_options: #Delete the entire trimming_options section if no trimming is desired
    paired_end_mode: true
    cutadapt_args: --nextseq-trim 13 -u 3 -m 20 --trim-n -a AGATCGGAAGAG -A AGATCGGAAGAG
alignment_options:
    read_length: 150
fastq_screen: #Delete the entire fastq_screen section if fastq_screen not desired
    reference_basedir: /nfs/turbo/umms-brcfpipeline/references/fastq_screen
    aligner: bowtie2
    subset: 100000
    species: human
diffex:
    count_min_cutoff: 1 #Filter lowly expressed genes using this cutoff
    #The following is an example Diffex section. Additional sections can be added
    #which will produce results in parallel directories
    #The parent node forms the name of directory for that model, in this case model_treatment.
    model_treatment:
        linear_fold_change: 1.5
        adjustedPValue: 0.05
        #Several contrasts of the form testVal_v_referenceVal can be listed here.
        #These contrasts will be pulled from the same DESeqDataset
        contrasts:
        -   drug_v_control
        DESeq2:
            #The design is used when initializing the dataset. Note that this is design is
            #currently not used when generating the normalized count tables
            design: ~ treatment
            #The factor name is used within the diffex Rscripts. See results notes below
            factor_name: treatment
            #The following parameters are directly parsed by R
            #and used within the call to DESeq2().
            #The imported DESeqDataset is passed by default and isn't listed here.
            DESeq2:
                betaPrior: true
            #The below parameters are also parsed by R and used to call results() {DESeq2}.
            #The initialized DESeqDataset is passed by default and isn't listed here.
            #There are several ways to list the contrast parameter. This way produces results equivalent to
            #previous Watermelon pipelines. The variables factorName, testName, & referenceName are defined
            #within the Rscript. Using the first contrast as an example this would parse to
            #list('treatmentdrug', 'treatmentcontrol'), which are the two elements
            #of resultsNames() relevant for that comparison.
            results:
                contrast: list(paste0(factorName, testName), paste0(factorName, referenceName))
