input_dir:
    "/ccmb/BioinfCore/SoftwareDev/projects/Watermelon_spike/Tronson_RS1_tests/test_data/inputs/00-multiplexed_reads"
alignment_output_dir:
    "alignment_results"
diffex_output_dir:
    "diffex_results"

main_factors:  yes     ^  yes   ^    no          ^   no
phenotypes:    gender  ^  diet  ^    male.diet   ^   female.diet
samples:
    Sample_61483: Me     ^   HF   ^      HF        ^
    Sample_61484: Me     ^   ND   ^      ND        ^
    Sample_61485: Me     ^   HF   ^      HF        ^
    Sample_61486:       ^   ND   ^                ^    ND
    Sample_61504: Fe     ^   HF   ^                ^    HF
    Sample_61505: Fe     ^   HF   ^                ^    HF
    Sample_61506: Fe     ^   DRG  ^                ^    DRG
    Sample_61490:       ^   DRG  ^                ^    DRG

comparisons:
    gender:
    - Me_v_Fe
    diet:
    - HF_v_ND
    - HF_v_DRG
    - ND_v_DRG
    male.diet:
    - HF_v_ND
    female.diet:
    - HF_v_ND
    - HF_v_DRG

fold_change:
    1.5

deseq2_adjustedPValue:
    0.05

trimming_options:
    base_quality_5prime: 0
    base_quality_3prime: 0
    trim_length_5prime: 0
    trim_length_3prime: 3

insert_size:
    downsample_readcount: 30000
    pair_length: 500

alignment_options:
    transcriptome_only: True
    library_type: fr-unstranded  # fr-firststrand # fr-secondstrand

genome:
    mm10

references:
#path to reference gtf file
    gtf: /ccmb/BioinfCore/SoftwareDev/projects/Watermelon_spike/Tronson_RS1_tests/test_data/inputs/references/mm10_tronson/genes.gtf
#    gtf: /ccmb/BioinfCore/Reference_Genomes/programs/tophat/mouse/mm10/Mus_musculus/UCSC/mm10/Annotation/Genes
# path to dir with bowtie index
    bowtie2_index: /ccmb/BioinfCore/Reference_Genomes/programs/tophat/mouse/mm10/Mus_musculus/UCSC/mm10/Sequence/BowtieIndex/bowtie2
#    bowtie2_index: /ccmb/BioinfCore/Reference_Genomes/programs/tophat/mouse/mm10/Mus_musculus/UCSC/mm10/Sequence/BowtieIndex
# path to entrez gene info file
    entrez_gene_info: /ccmb/BioinfCore/SoftwareDev/projects/Watermelon/genome_annotations/entrez_gene_info/2016_09_02/gene_info
#    entrez_gene_info: /ccmb/BioinfCore/SoftwareDev/projects/Watermelon/genome_annotations/entrez_gene_info/2016_09_02
