# config created 2019-10-29 14:35:00
# To do:
# ------
# 1) Review genome and references
# 2) Review alignment, trimming, and fastq_screen options
# 3) Modify the diffex options - use the 'model_one' stanza as an example, and
#    set up the DESeq2 calls and results calls for the comparisons that match the analysis.

email:
    subject: watermelon_20191029_human
    to: trsaari@umich.edu
watermelon_version: 1.1.0
sample_description_file: /ccmb/BioinfCore/ActiveProjects/trsaari/sandbox/20191023_testing_simulated_data/samplesheet.csv
genome: GRCh38
references:
    fasta: /nfs/med-bfx-common/ENSEMBL_references/Homo_sapiens/GRCh38/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa
    gtf: /nfs/med-bfx-common/ENSEMBL_references/Homo_sapiens/GRCh38/Homo_sapiens.GRCh38.98.gtf
    annotation_tsv: /nfs/med-bfx-common/ENSEMBL_references/Homo_sapiens/GRCh38/Homo_sapiens.GRCh38.98_annotation.tsv
dirs:
    alignment_output: analysis_20191029_human/alignment_results
    diffex_output: analysis_20191029_human/diffex_results
    deliverables_output: analysis_20191029_human/deliverables
    input: /ccmb/BioinfCore/ActiveProjects/trsaari/sandbox/20191023_testing_simulated_data/inputs/01-source_samples
trimming_options: #Delete the entire trimming_options stanza if no trimming is desired
    base_quality_5prime: 0
    base_quality_3prime: 13
    trim_length_5prime: 3
    trim_length_3prime: 0
alignment_options:
    read_length: 100
fastq_screen:
    reference_basedir: /nfs/med-bfx-common/pipelines/Watermelon/references/fastq_screen
    aligner: bowtie2
    subset: 100000
    species: human
diffex:
    linear_fold_change: 1.5
    adjustedPValue: 0.05
    #The following is an example Diffex stanza. Additional stanzas can be added
    #which will produce results in parallel directories
    #The parent node (model name) forms the names of directories.
    model_one:
        #Several contrasts of the form testVal_v_referenceVal are listed.
        contrasts:
        -   case_v_control
        DESeq2:
            #The design is used when initializing the dataset. Note that this is design is
            #currently not used when generating the normalized count tables
            design: ~ group
            #The factor name is used within the diffex Rscripts. See results notes below
            factor_name: group
            #The following parameters are directly parsed by R
            #and used within the call to DESeq2().
            #The imported DESeq2Dataset is passed by default and isn't listed here.
            DESeq2:
                betaPrior: true
            #The below parameters are also parsed by R and used to call results() {DESeq2}.
            #The initialized DESeq2Dataset is passed by default and isn't listed here.
            #There are several ways to list the contrast parameter. This way produces results equivalent to
            #previous Watermelon pipelines. The variables factorName, testName, & referenceName are defined
            #within the Rscript. Using the first contrast as an example this would parse to
            #list('pheno.GendDM.male', 'pheno.GendNDM.male'), which are the two elements
            #of resultsNames() relevant for that comparison.
            results:
                contrast: list(paste0(factorName, testName), paste0(factorName, referenceName))
