# Based on /ccmb/BioinfCore/ActiveProjects/rcavalca/test_lumeng

fold_change: 1.5
adjustedPValue: 0.05

# # diffex_results/pheno/DESeq2/pheno^DM^NDM
# # diffex_results/pheno/ballgown
# pheno:
#     DESeq2:
#         DESeq2:
#             full: ~ 0 + pheno
#             reduced: ~ 0
#             betaPrior: FALSE
#             test: LRT
#         results:
#             contrasts:
#                 - [pheno, DM, NDM]
#     ballgown:
#         stattest:
#             pData: example_sample_description.csv
#             feature: transcript
#             meas: FPKM
#             covariate: pheno # And how do we ensure correct reference factor?
#
# # diffex_results/pheno_gender_corrected/DESeq2/pheno^DM^NDM
# # diffex_results/pheno_gender_corrected/ballgown
# pheno_gender_corrected:
#     DESeq2:
#         DESeq2:
#             full: ~ 0 + pheno + Gend
#             reduced: ~ 0 + Gend
#             betaPrior: FALSE
#             test: LRT
#         results:
#             contrasts:
#                 - [pheno, DM, NDM]
#     ballgown:
#         stattest:
#             pData: example_sample_description.csv
#             feature: transcript
#             meas: FPKM
#             covariate: pheno
#             adjustvars: Gend
#
# # Equivalent to ballgown sub-block above?
# # diffex_results/pheno_gender_corrected_alt_ballgown/ballgown
# pheno_gender_corrected_alt_ballgown:
#     ballgown:
#         stattest:
#             pData: example_sample_description.csv
#             feature: transcript
#             meas: FPKM
#             mod: ~ 0 + pheno + Gend
#             mod0: ~ 0 + Gend
#
# # diffex_results/pheno_male/DESeq2/pheno.male^DM.male^NDM.male
# # diffex_results/pheno_male/ballgown
# pheno_male:
#     DESeq2:
#         DESeq2:
#             full: ~ 0 + pheno.male
#             reduced: ~ 0
#             betaPrior: FALSE
#             test: LRT
#         results:
#             contrasts:
#                 - [pheno.male, DM.male, NDM.male] # Do we have to subset the data ourselves or will DESeq2 do it?
#     ballgown:
#         stattest:
#             pData: example_sample_description.csv
#             feature: transcript
#             meas: FPKM
#             covariate: pheno.male # Do we have to subset the data ourselves or will ballgown do it?

# Note we can do multiple contrasts within the same model in DESeq2, but not in ballgown
# diffex_results/pheno_gender/DESeq2/pheno.Gend_DM.male_NDM.male
# diffex_results/pheno_gender/DESeq2/pheno.Gend_DM.fem_NDM.fem
# diffex_results/pheno_gender/DESeq2/pheno.Gend_DM.fem_DM.male
# diffex_results/pheno_gender/DESeq2/pheno.Gend_NDM.fem_NDM.male

pheno_gender:
    DESeq2:
        DESeq2:
            full: ~ 0 + pheno.Gend
            betaPrior: FALSE
        results:
            contrasts:
                #TWS - These must be parsed by the Rscript, a list of lists is just flattened when passed-in via snakemake
                - pheno.Gend^DM.male^NDM.male
                - pheno.Gend^DM.fem^NDM.fem
                - pheno.Gend^DM.fem^DM.male
                - pheno.Gend^NDM.fem^NDM.male
