dirs:
  input: /ccmb/BioinfCore/ActiveProjects/rcavalca/test_lumeng/inputs/01-source_samples
  alignment_output: alignment_results
  diffex_output: diffex_results
  deliverables_output_dir: deliverables

genome: hg19
references:
    hisat2_index: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/hg19/HISAT2_index/hg19_noRibo
    bowtie2_index: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/hg19/Sequence/Bowtie2Index
    entrez_gene_info: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/entrez_gene_info/2016_09_02/gene_info
    gtf: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/hg19/hg19_noRibo.gtf

sample_description_file: example_sample_description.csv

alignment_options:
    read_length: 50
    library_type: fr-unstranded
    transcriptome_only: true

trimming_options:
    base_quality_3prime: 13
    base_quality_5prime: 0
    trim_length_3prime: 0
    trim_length_5prime: 3

comparison_config: example_comparisons.yaml
