# config created 2020-07-21 17:28:14
# To do:
# ------
# 1) Review genome and references
# 2) Review alignment, trimming, and fastq_screen options
# 3) Modify the diffex options - use the 'model_one' stanza as an example, and
#    set up the DESeq2 calls and results calls for the comparisons that match the analysis.

email:
    subject: watermelon_test
    to: trsaari@umich.edu
watermelon_version: 1.4.2
samplesheet: /nfs/med-bfx-activeprojects/trsaari/sandbox/20200720_wat_test/samplesheet.csv
genome: GRCh38
references:
    fasta: /nfs/med-bfx-common/ENSEMBL_references/Homo_sapiens/GRCh38/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa
    gtf: /nfs/med-bfx-common/ENSEMBL_references/Homo_sapiens/GRCh38/Homo_sapiens.GRCh38.98.gtf
    annotation_tsv: /nfs/med-bfx-common/ENSEMBL_references/Homo_sapiens/GRCh38/Homo_sapiens.GRCh38.98_annotation.tsv
dirs:
    alignment_output: analysis_test/alignment_results
    diffex_output: analysis_test/diffex_results
    deliverables_output: analysis_test/deliverables
    report_output: analysis_test/report
    input: /nfs/med-bfx-activeprojects/trsaari/sandbox/20200720_wat_test/inputs/01-source_samples
trimming_options: #Delete the entire trimming_options stanza if no trimming is desired
    paired_end_mode: true
    base_quality_5prime: 0
    base_quality_3prime: 13
    trim_length_5prime: 3
    trim_length_3prime: 0
alignment_options:
    read_length: 100
fastq_screen: #Delete the entire fastq_screen stanza if fastq_screen not desired
    reference_basedir: /nfs/turbo/umms-brcfpipeline/references/fastq_screen
    aligner: bowtie2
    subset: 100000
    species: human
diffex:
    count_min_cutoff: 1 #Filter lowly expressed genes using this cutoff
    #The following is an example Diffex stanza. Additional stanzas can be added
    #which will produce results in parallel directories
    #The parent node forms the name of directory for that model, in this case model_treatment.
    model_treatment:
        linear_fold_change: 1.5
        adjustedPValue: 0.05
        #Several contrasts of the form testVal_v_referenceVal can be listed here.
        #These contrasts will be pulled from the same DESeqDataset
        contrasts:
        -   drug_v_control
        DESeq2:
            #The design is used when initializing the dataset. Note that this is design is
            #currently not used when generating the normalized count tables
            design: ~ treatment
            #The factor name is used within the diffex Rscripts. See results notes below
            factor_name: treatment
            #The following parameters are directly parsed by R
            #and used within the call to DESeq2().
            #The imported DESeqDataset is passed by default and isn't listed here.
            DESeq2:
                betaPrior: true
            #The below parameters are also parsed by R and used to call results() {DESeq2}.
            #The initialized DESeqDataset is passed by default and isn't listed here.
            #There are several ways to list the contrast parameter. This way produces results equivalent to
            #previous Watermelon pipelines. The variables factorName, testName, & referenceName are defined
            #within the Rscript. Using the first contrast as an example this would parse to
            #list('treatmentdrug', 'treatmentcontrol'), which are the two elements
            #of resultsNames() relevant for that comparison.
            results:
                contrast: list(paste0(factorName, testName), paste0(factorName, referenceName))
