hg19:
    genome: hg19
    fastq_screen:
        species: human
    references:
        gtf: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/hg19/hg19_noRibo.gtf
        hisat2_index: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/hg19/HISAT2_index/hg19_noRibo
        bowtie2_index: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/hg19/Sequence/Bowtie2Index
        entrez_gene_info: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/entrez_gene_info/2016_09_02/gene_info
GRCh37:
    genome: GRCh37
    fastq_screen:
        species: human
    references:
        gtf: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/GRCh37/genes.gtf
        bowtie2_index: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/GRCh37/Sequence/Bowtie2Index
        entrez_gene_info: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/entrez_gene_info/2016_09_02/gene_info
        hisat2_index: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/GRCh37/HISAT2_index/GRCh37_genes
mm10:
    genome: mm10
    fastq_screen:
        species: mouse
    references:
        gtf: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/mm10/mm10_noRibo.gtf
        hisat2_index: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/mm10/HISAT2_index/mm10_noRibo
        bowtie2_index: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/mm10/Sequence/Bowtie2Index
        entrez_gene_info: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/entrez_gene_info/2016_09_02/gene_info
rn5:
    genome: rn5
    fastq_screen:
        species: rat
    references:
        gtf: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/rn5/genes.gtf
        bowtie2_index: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/rn5/Sequence/Bowtie2Index
        entrez_gene_info: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/entrez_gene_info/2016_09_02/gene_info
        hisat2_index: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/rn5/HISAT2_index/rn5_genes
ce10:
    genome: ce10
    fastq_screen:
        species: celegans
    references:
        gtf: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/ce10/genes.gtf
        bowtie2_index: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/ce10/Sequence/Bowtie2Index
        entrez_gene_info: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/entrez_gene_info/2016_09_02/gene_info
        hisat2_index: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/ce10/HISAT2_index/ce10_genes
ce11:
    genome: ce11
    fastq_screen:
        species: celegans
    references:
        gtf: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/ce11/genes.gtf
        bowtie2_index: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/ce11/Sequence/Bowtie2Index
        entrez_gene_info: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/entrez_gene_info/2016_09_02/gene_info
        hisat2_index: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/ce11/HISAT2_index/ce11_genes
WBS235:
    genome: WBS235
    fastq_screen:
        species: celegans
    references:
        gtf: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/WBS235/genes.gtf
        bowtie2_index: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/WBS235/Sequence/Bowtie2Index
        entrez_gene_info: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/entrez_gene_info/2016_09_02/gene_info
        hisat2_index: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/WBS235/HISAT2_index/WBS235_genes
GRCz10:
    genome: GRCz10
    fastq_screen:
        species: zebrafish
    references:
        gtf: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/GRCz10/genes.gtf
        bowtie2_index: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/GRCz10/Sequence/Bowtie2Index
        entrez_gene_info: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/entrez_gene_info/2016_09_02/gene_info
        hisat2_index: /ccmb/BioinfCore/Common/pipelines/Watermelon/references/GRCz10/HISAT2_index/GRCz10_genes
