subtitle: ''
intro_text: ''

no_version_check: True

export_plot_formats:
  - png

fn_ignore_paths:
  - '*/.log/'
  - '*/biotype/*'

extra_fn_clean_exts:
  - '.genome'

module_order:
  - star:
      path_filters:
        - '*rsem_star_align*'
  - fastqc:
      name: 'FastQC (trimmed sequences)'
      path_filters:
        - '*fastqc_reads*'
  - fastqc:
      name: 'FastQC (aligned reads)'
      path_filters:
        - '*fastqc_align*'
  - fastq_screen
