subtitle: ''
intro_text: ''

no_version_check: True

export_plot_formats:
  - png

fn_ignore_paths:
  - '*/.log/'
  - '*/biotype/*'

extra_fn_clean_exts:
  - '.genome'

rseqc_sections:
  - read_distribution

module_order:
  - star:
      path_filters:
        - '*rsem_star_align*'
  - fastqc:
      name: 'FastQC'
      path_filters:
        - '*fastqc_reads*'
  - rseqc:
      path_filters:
        - '*_read_distribution.txt'
  - fastq_screen

sp:
  star:
    fn: '*.log'
