input_dir:
    "/ccmb/BioinfCore/SoftwareDev/projects/Watermelon_spike/Oshea_RS1_hg19_stranded/watermelon/input/00-multiplexed_reads"

samples:
    Sample_67517: WT.notr
    Sample_67518: Cont.notr
    Sample_67519: Cont.notr
    Sample_67520: Cont.notr
    Sample_67521: Cont.notr
    Sample_67522: BP.notr
    Sample_67523: BP.notr
    Sample_67524: BP.notr
    Sample_67525: BP.notr

comparisons:
    Cont.notr_v_WT.notr: Cont.notr_v_WT.notr                      #comparison1 (rtagett)
    Cont.notr_v_BP.notr:  Cont.notr_v_BP.notr                   #comparison2 (rtagett)

fold_change:
    1.5

trimming_options:
    base_quality_5prime: 0
    base_quality_3prime: 13
    trim_length_5prime: 3
    trim_length_3prime: 0

alignment_options:
    transcriptome_only: True
    library_type: 2  # 0, 1, 2

genome:
    hg19

references:
#path to reference gtf file
    gtf: /ccmb/BioinfCore/ActiveProjects/rtagett/noRiboGTFs/noRibo_human.gtf
# path to dir with bowtie index
    bowtie2_index: /ccmb/BioinfCore/Projects/Manjusha/Genomes/iGenomes/Homo_sapiens_UCSC_hg19/Homo_sapiens/UCSC/hg19/Sequence/Bowtie2Index
# path to entrez gene info file
    entrez_gene_info: /ccmb/BioinfCore/SoftwareDev/projects/Watermelon/genome_annotations/entrez_gene_info/2016_09_02/gene_info
