dirs:
  alignment_output: alignment_results
  diffex_output: diffex_results
  deliverables_output: deliverables

fold_change:
    1.5

deseq2_adjustedPValue:
    0.05

insert_size:
    downsample_readcount: 30000
    pair_length: 500

trimming_options:
    base_quality_5prime: 0
    base_quality_3prime: 13
    trim_length_5prime: 3
    trim_length_3prime: 0

alignment_options:
    transcriptome_only: True
    library_type: fr-unstranded   #fr-firststrand   #fr-secondstrand
    read_length: 50

fastq_screen:
    reference_basedir: /nfs/med-bfx-common/pipelines/Watermelon/references/fastq_screen
    aligner: bowtie2
    subset: 100000
