alignment_output_dir:
    "alignment_results/"
diffex_output_dir:
    "diffex_results/"
deliverables_output_dir:
    "deliverables/"

fold_change:
    1.5

deseq2_adjustedPValue:
    0.05

trimming_options:
    base_quality_5prime: 0
    base_quality_3prime: 13
    trim_length_5prime: 3
    trim_length_3prime: 0

alignment_options:
    transcriptome_only: True
    library_type: fr-unstranded   #fr-firststrand   #fr-secondstrand
