dirs:
  alignment_output: analysis{job_suffix}/alignment_results
  diffex_output: analysis{job_suffix}/diffex_results
  deliverables_output: analysis{job_suffix}/deliverables
  report_output: analysis{job_suffix}/report
report_info: #These strings are used directly in the report
    project_name: ExampleProject #Don't use spaces in project name. Will fail on cluster
    prep_description: 'Prior tissue or cell isolation along with generation of total RNA was performed by the researcher. Sequencing was performed by the UM Advanced Genomics Core, with libraries constructed and subsequently subjected to 150 paired end cycles on the NovaSeq-6000 platform (Illumina).'
    acknowledgement_text:
        It is important to document use of each Biomedical Research Core Facility by investigators in publications. This facilitates efforts to obtain funding for our Cores and their continued functioning. Please recognize the core’s contribution in the Acknowledgment section of your publications.


        “We acknowledge support from the Bioinformatics Core of the University of Michigan Medical School’s Biomedical Research Core Facilities.”


        If core staff have added scientific value to your project — made intellectual contributions in design, analysis and interpretation of data and/or manuscript writing, then please consider including them as co-authors in your publications.
    # Boolean value to determine whether to include text regarding follow-up.
    include_follow_up: True
    include_pct_dups: True
trimming_options: #Delete the entire trimming_options section if no trimming is desired
    paired_end_mode: True
    cutadapt_args: --nextseq-trim 13 -u 3 -m 20 --trim-n -a AGATCGGAAGAG -A AGATCGGAAGAG
alignment_options:
    read_length: 150
fastq_screen: #Delete the entire fastq_screen section if fastq_screen not desired
    reference_basedir: /nfs/turbo/umms-brcfpipeline/references/fastq_screen
    aligner: bowtie2
    subset: 100000
diffex:
    count_min_cutoff: 1 #Filter lowly expressed genes using this cutoff
    #The following is an example Diffex section. Additional sections can be added
    #which will produce results in parallel directories
    #The parent node forms the name of directory for that model, in this case model_treatment.
    model_treatment:
        linear_fold_change: 1.5
        adjustedPValue: 0.05
        #Several contrasts of the form testVal_v_referenceVal can be listed here.
        #These contrasts will be pulled from the same DESeqDataset
        contrasts:
            - drug_v_control
        DESeq2:
            #The design is used when initializing the dataset. Note that this is design is
            #currently not used when generating the normalized count tables
            design: ~ treatment
            #The factor name is used within the diffex Rscripts. See results notes below
            factor_name: treatment
            #The following parameters are directly parsed by R
            #and used within the call to DESeq2().
            #The imported DESeqDataset is passed by default and isn't listed here.
            DESeq2:
                betaPrior: TRUE
            #The below parameters are also parsed by R and used to call results() {DESeq2}.
            #The initialized DESeqDataset is passed by default and isn't listed here.
            #There are several ways to list the contrast parameter. This way produces results equivalent to
            #previous Watermelon pipelines. The variables factorName, testName, & referenceName are defined
            #within the Rscript. Using the first contrast as an example this would parse to
            #list('treatmentdrug', 'treatmentcontrol'), which are the two elements
            #of resultsNames() relevant for that comparison.
            results:
                contrast:
                    list(paste0(factorName, testName), paste0(factorName, referenceName))
