email:
  subject: watermelon_mm-dd-yyyy
  to: cgates@umich.edu

dirs:
  alignment_output: alignment_results
  diffex_output: diffex_results
  deliverables_output: deliverables

trimming_options:
    base_quality_5prime: 0
    base_quality_3prime: 13
    trim_length_5prime: 3
    trim_length_3prime: 0

alignment_options:
    transcriptome_only: True
    library_type: fr-unstranded #forward_reverse #reverse_forward
    read_length: 50

fastq_screen:
    reference_basedir: /nfs/med-bfx-common/pipelines/Watermelon/references/fastq_screen
    aligner: bowtie2
    subset: 100000

diffex:
    fold_change: 1.5
    adjustedPValue: 0.05
    #The following is an example DESeq2 stanza
    pheno_gender:
        DESeq2:
            DESeq2:
                full: ~ pheno.Gend
                betaPrior: TRUE
            results:
                contrasts:
                    - pheno.Gend^DM.male^NDM.male
                    - pheno.Gend^DM.fem^NDM.fem
                    - pheno.Gend^DM.fem^DM.male
                    - pheno.Gend^NDM.fem^NDM.male
