input_dir:
    "/ccmb/BioinfCore/SoftwareDev/projects/Watermelon_spike/Tronson_RS1_tests/Tronson_full_data/Watermelon/inputs/00-multiplexed_reads"
samples:
    Sample_61483: VVM
    Sample_61484: VVM
    Sample_61485: VVM
    Sample_61486: VLM
    Sample_61487: VLM
    Sample_61488: VLM
    Sample_61489: LVM
    Sample_61490: LVM
    Sample_61491: LVM
    Sample_61492: LLM
    Sample_61493: LLM
    Sample_61494: LLM
    Sample_61495: VVF
    Sample_61496: VVF
    Sample_61497: VVF
    Sample_61498: VLF
    Sample_61499: VLF
    Sample_61500: VLF
    Sample_61501: LVF
    Sample_61502: LVF
    Sample_61503: LVF
    Sample_61504: LLF
    Sample_61505: LLF
    Sample_61506: LLF

comparisons:
    VVF_v_LVF: VVF_v_LVF
    VVF_v_VLF: VVF_v_VLF
    VVF_v_LLF: VVF_v_LLF
    VVF_v_VVM: VVF_v_VVM
    LVF_v_VLF: LVF_v_VLF
    LVF_v_LLF: LVF_v_LLF
    LVF_v_VVM: LVF_v_VVM
    VLF_v_LLF: VLF_v_LLF
    VLF_v_VVM: VLF_v_VVM
    LLF_v_VVM: LLF_v_VVM
    VVM_v_VVF: VVM_v_VVF
    VLM_v_VVF: VLM_v_VVF
    LVM_v_LVF: LVM_v_LVF
    LLM_v_LVF: LLM_v_LVF

fold_change:
    1.5

trimming_options:
    base_quality_5prime: 0
    base_quality_3prime: 13
    trim_length_5prime: 3
    trim_length_3prime: 0

alignment_options:
    transcriptome_only: False
    library_type: 0  # 1   # 2

genome:
    mm10

references:
# path to reference gtf file
    gtf: /ccmb/BioinfCore/Reference_Genomes/programs/tophat/mouse/mm10/Mus_musculus/UCSC/mm10/Annotation/Genes/genes.gtf
# path to dir with bowtie index
    bowtie2_index: /ccmb/BioinfCore/Reference_Genomes/programs/tophat/mouse/mm10/Mus_musculus/UCSC/mm10/Sequence/BowtieIndex/bowtie2
# path to entrez gene info file
    entrez_gene_info: /ccmb/BioinfCore/SoftwareDev/projects/Watermelon/genome_annotations/entrez_gene_info/2016_09_02/gene_info

