#!/bin/bash
# Launches snakemake
# 9/27/2016 abhasi/cgates


export SCRIPT_NAME=`basename $0 .sh`
export LOG_DIR=logs
export LOG_FILE=${LOG_DIR}/${SCRIPT_NAME}.log

SNAKEMAKE_VERSION=$(snakemake --version 2>/dev/null)
if ! [[ $SNAKEMAKE_VERSION ]]; then
  echo "snakemake not found; is the python3 module loaded correctly? (contact bfxcore support for assistance)."
  exit 1
fi

set -e #script will fail on any error

EXPECTED_ARGS=1

if [[ $# -ne $EXPECTED_ARGS ]]; then
    echo "Usage: ${SCRIPT_NAME} {config_file}"
    echo "Example ${SCRIPT_NAME} ~/my_config.yaml" 
    exit 1
fi

export CONFIG_FILE=$1

if [[ ! -f $CONFIG_FILE ]]; then
    echo "ERROR: config file [${CONFIG_FILE}] cannot be read"
    echo "Usage: ${SCRIPT_NAME} {config_file}"
    echo "Example ${SCRIPT_NAME} ~/my_config.yaml" 
    exit 1
fi 


mkdir -p ${LOG_DIR}
echo Logging to ${LOG_FILE}
(
echo 0 > .watermelon.exitcode
set +e

snakemake --snakefile rnaseq.snakefile --configfile ${CONFIG_FILE} --cores 40 -T

SNAKEMAKE_EXIT=$?
if [[ $SNAKEMAKE_EXIT != 0 ]]; then
    echo 'ERROR: Snakemake encountered an unexpected error. Review config and contact bfxcore support.'
    echo $SNAKEMAKE_EXIT > .watermelon.exitcode
fi
) 2>&1 | tee $LOG_FILE

EXIT_CODE=$(cat .watermelon.exitcode)
exit ${EXIT_CODE}